### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by archenroot** [Ed-von-Schleck/shoco#38]
On large input file with words to train I get(the input csv file is actually just pure 1 column list):
```
zangetsu@venus: pts/11: 16 files 192Kb -> ./generate_compressor_model.py ~/tmp/csv-compress-string/my_events.csv -o shoco_model.h 
finding bigrams ... done.
Traceback (most recent call last):
  File "./generate_compressor_model.py", line 391, in <module>
    main()
  File "./generate_compressor_model.py", line 305, in main
    max_chr = ord(max(successors.keys())) + 1
TypeError: ord() expected string of length 1, but int found
```

**Comment by archenroot** [comment]
Python 3 related...

**Comment by charmander** [comment]
See #18
