### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by archenroot** [Ed-von-Schleck/shoco#39]
```
zangetsu@venus: pts/11: 16 files 192Kb -> ./generate_compressor_model.py --split=whitespace --strip=punctuation README.md
Traceback (most recent call last):
  File "./generate_compressor_model.py", line 391, in <module>
    main()
  File "./generate_compressor_model.py", line 287, in main
    chunks = list(chunkinator(args.file, args.split, args.strip))
  File "./generate_compressor_model.py", line 245, in chunkinator
    for chunk in chunks:
  File "./generate_compressor_model.py", line 242, in <genexpr>
    chunks = itertools.chain.from_iterable(re.split(b"[" + WHITESPACE + "]", data) for data in all_in)
TypeError: can't concat str to bytes

```

Probably related to fact it is python2 related and I run on v3...

**Comment by charmander** [comment]
See #18
